version: '3'

services:
  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - NODE_ENV=development 